language: php

php:
 - 5.6

install:
  # Apache needs to be able to read the docroot directory and all parents
  - chmod 755 ~/
  - sudo apt-get update
  - sudo apt-get install apache2
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod headers rewrite actions proxy proxy_fcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # Create the docroot and index.php
  - mkdir docroot
  # configure apache virtual hosts
  - sudo cp -f tests/apache.conf.tpl /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 reload
  # Install out python dependencies
  - pip install --user -r requirements-test.txt

script:
  - python ./test.py

after_failure:
  - sudo cat /var/log/apache2/access.log
  - sudo cat /var/log/apache2/error.log
  - cat docroot/.htaccess
